### ISSUE TITLE
Website changed?

### ISSUE THREAD

**Issue by SteveM363** [isonium/CloudAtCost-Wallet#6]
Getting a 200 error when running. Found that the transaction URI (https://wallet.cloudatcost.com/transaction) is giving a 404 error.  I attempted to appended /btc but that only lists a small number of transactions; in my case 411 but could be days limited, back to 2022-04-19 00:01 when the last transaction was 25/04/2022 20:01:00.

Last run successfully was around 13 hours ago so change has happened recently. Was using a version about 3 months old, but pulled latest and same result, so fairly sure it is an issue at their end.

Error message:
Traceback (most recent call last):
  File "./cac.py", line 698, in <module>
    main()
  File "./cac.py", line 129, in main
    html = load_transactions(config)
  File "./cac.py", line 492, in load_transactions
    assert browser.code == 200, "Failed to Load Transactions"
AssertionError: Failed to Load Transactions

**Comment by mrd0n** [comment]
I'm seeing the same error.

> Loading 'coinbasepro.csv'...
Updating 'coinbasepro.csv'....loaded 165 records.
Config file config1.csv loaded...
Accessing https://wallet.cloudatcost.com/
Logging In...
Generating 2FA Code...
Loading Transactions...
Traceback (most recent call last):
  File "./cac.py", line 781, in <module>
    main()
  File "./cac.py", line 128, in main
    html = load_transactions(config)
  File "./cac.py", line 539, in load_transactions
    assert browser.code == 200, "Failed to Load Transactions"
AssertionError: Failed to Load Transactions

**Comment by mrd0n** [comment]
In the browser (https://wallet.cloudatcost.com/transaction/btc), I only see back to April 19 - the page is only providing about a week of transaction history.  I hope it is a bug on their site and not what they intend to provide going forward...

**Comment by isonium** [comment]
All transactions option is only showing 1 week of transactions.  I hope they fix it soon.  Will update code when I know more.

**Comment by isonium** [comment]
I updated the URL in the code, so it will download transactions again, but CloudAtCost will need to provide a way to download all transactions for the program to work as it did before.

**Comment by SteveM363** [comment]
I think you updated the url in the wrong line, it needs to be the transactionURL not the walletURL that ends in /btc (or maybe both, but I don't see walletURL being used)

**Comment by isonium** [comment]
> I think you updated the url in the wrong line, it needs to be the transactionURL not the walletURL that ends in /btc (or maybe both, but I don't see walletURL being used)

transactionURL is what shows as changed.  walletURL as of right now is unused.

"    config["transactionURL"] = config["baseURL"]+"transaction/btc""

**Comment by isonium** [comment]
I contacted CaC support and received the following response.

"We will be bringing back a more organized view in the near future."
